[build]
  functions = "functions" # Le répertoire contenant vos fonctions serverless

[[redirects]]
  from = "/api/*" # Un chemin d'accès qui déclenchera la fonction
  to = "/.netlify/functions/myFunction" # Le chemin de la fonction serverless
  status = 200