[build]
  functions = "functions" # Le répertoire contenant vos fonctions serverless

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  DB_FILE = "database/database.sqlite"